ALTER TABLE users DROP COLUMN name;
ALTER TABLE users DROP COLUMN status;
ALTER TABLE users ADD COLUMN firstName VARCHAR(50) NOT NULL;
ALTER TABLE users ADD COLUMN lastName VARCHAR(50) NOT NULL;
ALTER TABLE users ADD COLUMN phoneNumber VARCHAR(50) NOT NULL;